### PR TITLE
small steps to fix course_region mess

### PR DESCRIPTION
**Pull request by mhgoldman**
I haven't quite figured out if the way I'm dealing with the participant <--> course_region relationship makes any sense. This fix feels like sort of a cop-out, but basically here's what I've done:

- Add logic to the validations on Participant so that a Participant is not valid if its Course Region is mapped to a different Region than its Event's Region. (Bonus points if you have any idea what that means!)
- The issue we ran into today should be preventable simply by disallowing an Event's Course to be changed. Thinking about it more, a Course seems like such a fundamental property of an Event that I feel this is OK, so I'm implemented that.

Please let me know if you have any other thoughts. It's entirely possible that there's a more elegant object relational model than having Participants belong to Events, Events belonging to Courses, and both Participants and Courses belonging to CourseRegions. But I just can't figure one out!

### CODE REVIEW

**Comment by eliotsykes** [comment]
What you've done so far looks good. I'm currently thinking the model is OK and the problem did indeed lie in the validation.

I'm wondering out loud if this would have been a good spot to use the optional scope argument available on `belongs_to` and `has_many`. Might be worth trying on a spike. It would allow us to enforce via SQL that the course_region on a participant is also one of the course_regions associated with the participant.event.course.course_regions.

These are incomplete notes to accompany my wonderings. We can discuss further on a call.

```ruby
class Participant ...

  # The conditions in the scope would make it so the course_region must have a course_id matching
  # the course.id. Would need experimenting.
  belongs_to :course_region, ->(course_region) { where(...conditions to figure out...) }
  has_one :course, through: :event
  ...
end

class CourseRegion ...
  has_many :participants, ->(participant) { where(...conditions to figure out...) }

  ...
end
```

**Comment by mhgoldman** [comment]
Thanks Eliot. I took at a look at this, but couldn't figure it out. With
the lambda, self is the course_region. I didn't see a way to get a
reference to the Participant, and I couldn't find a way to get a reference
to the Participant itself, which meant I couldn't get its event's course's
course_regions to validate against.

**Comment by eliotsykes** [comment]
> Within the lambda, self is the course_region

@mhgoldman Its possible to pass the `participant` in, I gave the lambda the wrong argument name so its was completely misleading. 

```diff
class Participant ...

- belongs_to :course_region, ->(course_region) { where(...conditions to figure out...) },
+   belongs_to :course_region, ->(participant) { where('...', participant.foo) },  
```

Regardless the more I've thought about this I think the validation is the right way to deal with this **and** to tweak the model. The scope idea above wasn't a good one, apologies for that.

Instead, what do you think about having a participant directly associated with a Region instead of a CourseRegion? There are 2 ways to navigate to a Course from a Participant currently, this would remove that so you can only get to the Participant's Course through participant.event.course. Can chat more on call today.

**Comment by mhgoldman** [comment]
Yeah, I thought about that. I couldn't convince myself there was a huge
difference either way, but look forward to hearing your perspective.

It seemed that either way, you'd need a custom validation on Participant,
to test that either

participant.course_region.course == participant.event.course

or

participant.event.course_regions.map(&:region).include?(participant.region)

In addition, when we want to go provision a participant's Skytap
environment, we will need to get a reference to the CourseRegion (which
will be linked to a Skytap template ID, although that's not in place yet).
If Participant belongs to CourseRegion, that's an easier lookup
(participant.course_region.skytap_template_id, for example) compared to if
it belonged to Region (which would be something like
participant.event.course_regions.find_by(region:
participant.region).skytap_template_id.

I don't think it's a huge deal either way, but off the bat, I'm not sure I
see it being a big win to change it. But again, I could easily be missing
something so let me know your thoughts.

**Pull request merged**
